In [1]:
%%capture
# Data science
import numpy as np
import pandas as pd

# Data visualization
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib.colors import to_hex
%matplotlib inline
from fasteda import fast_eda

from sklearn.model_selection import train_test_split, KFold, StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, roc_auc_score, f1_score, \
    mean_squared_error, mean_absolute_error, r2_score
from lightgbm import LGBMClassifier, plot_importance, LGBMRegressor

import optuna
from optuna.samplers import TPESampler

import math
import warnings
import requests
from datetime import date
from mkl_random.mklrand import shuffle
warnings.filterwarnings('ignore')

# Initialization
## Import

In [2]:
df = pd.read_csv("unified_mycotoxins_fungi_clean.csv")
df2 = pd.read_csv("target_origin_zen_zan_weather_ready_strict_field_storage.csv")

In [3]:
print(f'The Train dataset has {df.shape[0]} rows and {df.shape[1]} columns')
df.describe()

The Train dataset has 11882 rows and 15 columns

        sample_year  toxin_value_raw  toxin_value_standardized_ug_kg
count  11798.000000      4604.000000                     4604.000000
mean    2019.655874       105.534331                      885.314699
std        6.913805      3873.135828                     4751.704980
min     1970.000000         0.000000                        0.000000
25%     2020.000000         0.000000                        0.000000
50%     2021.000000         0.097900                       15.000000
75%     2022.000000         4.257500                      259.925000
max     2022.000000    258000.000000                   258000.000000

In [5]:
display('Datas:', df, 'Datas2:', df2)

'Datas:'

,sample_id,source_dataset,crop_type,location_country,location_continent,timestamp,sample_year,toxin_name,toxin_value_raw,toxin_unit,toxin_value_standardized_ug_kg,toxin_detected,fungal_species,association_type,original_metadata
0,SUPP_INC_0,Supplementary Material 1 (Included studies),Cowpeas (Vigna unguiculata),Unknown,Africa,2000s,2009.0,Aflatoxins,NaN,ug/kg,NaN,True,A. flavus,Reported,"{""reference"": ""Houssou et al. (2009)"", ""title""..."
1,SUPP_INC_0,Supplementary Material 1 (Included studies),Cowpeas (Vigna unguiculata),Unknown,Africa,2000s,2009.0,Aflatoxins,NaN,ug/kg,NaN,True,Fusarium spp,Reported,"{""reference"": ""Houssou et al. (2009)"", ""title""..."
2,SUPP_INC_0,Supplementary Material 1 (Included studies),Cowpeas (Vigna unguiculata),Unknown,Africa,2000s,2009.0,Fumonisins,NaN,ug/kg,NaN,True,A. flavus,Reported,"{""reference"": ""Houssou et al. (2009)"", ""title""..."
3,SUPP_INC_0,Supplementary Material 1 (Included studies),Cowpeas (Vigna unguiculata),Unknown,Africa,2000s,2009.0,Fumonisins,NaN,ug/kg,NaN,True,Fusarium spp,Reported,"{""reference"": ""Houssou et al. (2009)"", ""title""..."
4,SUPP_INC_1,Supplementary Material 1 (Included studies),Beans (Phaseolus vulgaris),Unknown,Africa,2010s,2019.0,Aflatoxins,NaN,ug/kg,NaN,True,Aspergillus flavus,Known Producer,"{""reference"": ""Ingenbleek et al. (2019)"", ""tit..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11877,MYCO_2797,mycotoxins_clean.csv (Lithuania Cereal Monitor...,Maize grain (feed),Lithuania,Europe,2022-12-14,2022.0,T-2 Toxin,NaN,mg/kg,NaN,False,Fusarium poae,Known Producer,"{""sample_point"": ""E101A"", ""analytical_method"":..."
11878,MYCO_2797,mycotoxins_clean.csv (Lithuania Cereal Monitor...,Maize grain (feed),Lithuania,Europe,2022-12-14,2022.0,T-2 Toxin,NaN,mg/kg,NaN,False,Fusarium langsethiae,Known Producer,"{""sample_point"": ""E101A"", ""analytical_method"":..."
11879,MYCO_2798,mycotoxins_clean.csv (Lithuania Cereal Monitor...,"Cereal grain / crop (feed, code: A0BTV)",Lithuania,Europe,2022-12-05,2022.0,T-2 Toxin,NaN,mg/kg,NaN,False,Fusarium sporotrichioides,Known Producer,"{""sample_point"": ""Transformateur/Fabricant"", ""..."
11880,MYCO_2798,mycotoxins_clean.csv (Lithuania Cereal Monitor...,"Cereal grain / crop (feed, code: A0BTV)",Lithuania,Europe,2022-12-05,2022.0,T-2 Toxin,NaN,mg/kg,NaN,False,Fusarium poae,Known Producer,"{""sample_point"": ""Transformateur/Fabricant"", ""..."
11881,MYCO_2798,mycotoxins_clean.csv (Lithuania Cereal Monitor...,"Cereal grain / crop (feed, code: A0BTV)",Lithuania,Europe,2022-12-05,2022.0,T-2 Toxin,NaN,mg/kg,NaN,False,Fusarium langsethiae,Known Producer,"{""sample_point"": ""Transformateur/Fabricant"", ""..."

'Datas2:'

,origin_country_code,origin_country_label_fr,reporting_country_code,reporting_country_name,sample_country_code,sample_country_name,sample_date,sample_year,sample_month,sample_day,crop_group,product_name,sampling_point,param_name,zen_detected,zen_value_ug_kg,lod_ug_kg,loq_ug_kg,result_status,result_type,origin_matches_reporting_country,origin_matches_sample_country,sampling_strategy,program_type,sample_method,source_archive,source_file,resId_A
0,CZ,Tchequie,CZ,Czechia,CZ,Czechia,2019-02-20,2019,2,20,barley,Barley grain (feed),Primary production,Zearalenone,no,NaN,NaN,20.0,not_quantified_below_loq,Non Quantified Value ( less than LOQ),yes,yes,Objective sampling,Official (National) programme,NaN,CZ_latest_15410924_contaminants.zip,OCC_CHEMMON2020_CZ_2019.ZIP/OCC_CHEMMON2020_CZ...,CD4F4D661B734AD9E74B94A279E30233
1,CZ,Tchequie,CZ,Czechia,CZ,Czechia,2019-03-18,2019,3,18,barley,Barley grain (feed),Primary production,Zearalenone,no,NaN,NaN,20.0,not_quantified_below_loq,Non Quantified Value ( less than LOQ),yes,yes,Objective sampling,Official (National) programme,NaN,CZ_latest_15410924_contaminants.zip,OCC_CHEMMON2020_CZ_2019.ZIP/OCC_CHEMMON2020_CZ...,41CB40673B11DFD3300D20756321752A
2,CZ,Tchequie,CZ,Czechia,CZ,Czechia,2019-03-26,2019,3,26,barley,Barley grain (feed),Storage,Zearalenone,no,NaN,NaN,20.0,not_quantified_below_loq,Non Quantified Value ( less than LOQ),yes,yes,Objective sampling,Official (National) programme,NaN,CZ_latest_15410924_contaminants.zip,OCC_CHEMMON2020_CZ_2019.ZIP/OCC_CHEMMON2020_CZ...,356CFC6AF1743F0E38EAACE24AD1EE34
3,CZ,Tchequie,CZ,Czechia,CZ,Czechia,2019-10-23,2019,10,23,barley,Barley grain (feed),Storage,Zearalenone,no,NaN,NaN,20.0,not_quantified_below_loq,Non Quantified Value ( less than LOQ),yes,yes,Objective sampling,Official (National) programme,NaN,CZ_latest_15410924_contaminants.zip,OCC_CHEMMON2020_CZ_2019.ZIP/OCC_CHEMMON2020_CZ...,02DB9AA1D3A5A2F7F7383CCCAF04B6E8
4,CZ,Tchequie,CZ,Czechia,CZ,Czechia,2020-02-12,2020,2,12,barley,Barley grain (feed),Storage,Zearalenone,no,NaN,NaN,20.0,not_quantified_below_loq,Non Quantified Value ( less than LOQ),yes,yes,Objective sampling,Official (National) programme,NaN,CZ_latest_15410924_contaminants.zip,OCC_CHEMMON2021_CZ_2020.ZIP/OCC_CHEMMON2021_CZ...,E0EB9B82C93581D42418FEA7CF28BADE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,SK,Slovaquie,SK,Slovakia,SK,Slovakia,2023-09-19,2023,9,19,wheat,Common wheat grain,Primary production,Zearalenone,no,NaN,NaN,1.0,not_quantified_below_loq,Non Quantified Value ( less than LOQ),yes,yes,Selective sampling,Official (National) programme,Official sampling,SK_latest_15411469_contaminants.zip,OCC_CHEMMON2024_SK_2023.ZIP/OCC_CHEMMON2024_SK...,B74BFB4877BB720A50800B3B2A778D77
671,SK,Slovaquie,SK,Slovakia,SK,Slovakia,2023-09-29,2023,9,29,wheat,Common wheat grain,Primary production,Zearalenone,no,NaN,3.0,10.0,not_quantified_below_loq,Non Quantified Value ( less than LOQ),yes,yes,Selective sampling,Official (National) programme,Official sampling,SK_latest_15411469_contaminants.zip,OCC_CHEMMON2024_SK_2023.ZIP/OCC_CHEMMON2024_SK...,2A9C36E2DBFAFB64CC108370298CD965
672,SK,Slovaquie,SK,Slovakia,SK,Slovakia,2023-10-03,2023,10,3,wheat,Common wheat grain,Primary production,Zearalenone,no,NaN,NaN,8.0,not_quantified_below_loq,Non Quantified Value ( less than LOQ),yes,yes,Selective sampling,Official (National) programme,Official sampling,SK_latest_15411469_contaminants.zip,OCC_CHEMMON2024_SK_2023.ZIP/OCC_CHEMMON2024_SK...,310177CA51EE0AC37A0EA8389CAB5564
673,SK,Slovaquie,SK,Slovakia,SK,Slovakia,2023-10-23,2023,10,23,wheat,Common wheat grain,Primary production,Zearalenone,no,NaN,NaN,1.0,not_quantified_below_loq,Non Quantified Value ( less than LOQ),yes,yes,Selective sampling,Official (National) programme,Official sampling,SK_latest_15411469_contaminants.zip,OCC_CHEMMON2024_SK_2023.ZIP/OCC_CHEMMON2024_SK...,72554C183712F1986234C00F4A63BFC4
674,SK,Slovaquie,SK,Slovakia,SK,Slovakia,2023-11-06,2023,11,6,wheat,Common wheat grain,Primary production,Zearalenone,no,NaN,NaN,8.0,not_quantified_below_loq,Non Quantified Value ( less than LOQ),yes,yes,Selective sampling,Official (National) programme,Official sampling,SK_latest_15411469_contaminants.zip,OCC_CHEMMON2024_SK_2023.ZIP/OCC_CHEMMON2024_SK...,D25751426DB813350B94A2BCD4B94D14

## Summary

In [6]:
def summary(df):
    summ = pd.DataFrame(df.dtypes, columns=['data type'])
    summ['#missing'] = df.isnull().sum().values
    summ['Duplicate'] = df.duplicated().sum()
    summ['#unique'] = df.nunique().values
    desc = pd.DataFrame(df.describe(include='all').transpose())
    if 'min' in desc.columns:
        summ['min'] = desc['min'].values
    if 'max' in desc.columns:
        summ['max'] = desc['max'].values
    if 'mean' in desc.columns:
        summ['avg'] = desc['mean'].values
    if 'std' in desc.columns:
        summ['std dev'] = desc['std'].values
    if 'top' in desc.columns:
        summ['top value'] = desc['top'].values
    if 'freq' in desc.columns:
        summ['Freq'] = desc['freq'].values

    return summ

In [7]:
summary(df).style.background_gradient()

# Diagrams
## Showplot

In [9]:
def showplot(columnname, df):
    plt.rcParams['figure.facecolor'] = 'white'
    plt.rcParams['axes.facecolor'] = 'white'
    fig, ax = plt.subplots(1, 2, figsize=(10, 4))
    ax = ax.flatten()

    value_counts = df[columnname].value_counts()
    labels = value_counts.index.tolist()

    colors = [to_hex(c) for c in sns.color_palette("Set2", len(labels))]
    color_map = dict(zip(labels, colors))

    # Donut
    ax[0].pie(
        value_counts,
        autopct='%1.1f%%',
        textprops={'size': 9, 'color': 'white', 'fontweight': 'bold'},
        colors=[color_map[label] for label in labels],
        wedgeprops=dict(width=0.35),
        startangle=80,
        pctdistance=0.85
    )
    centre_circle = plt.Circle((0, 0), 0.6, fc='white')
    ax[0].add_artist(centre_circle)

    # Bar chart
    sns.countplot(
        data=df,
        y=columnname,
        hue=columnname,
        order=labels,
        hue_order=labels,
        palette=color_map,
        saturation=1,
        dodge=False,
        ax=ax[1],
        legend=False
    )

    for i, v in enumerate(value_counts):
        ax[1].text(v + 1, i, str(v), color='black', fontsize=10, va='center')

    sns.despine(left=True, bottom=True)
    ax[1].set_ylabel(None)
    ax[1].set_xlabel("")
    ax[1].set_xticks([])
    fig.suptitle(columnname, fontsize=15, fontweight='bold')
    plt.tight_layout(rect=[0, 0, 0.85, 1])
    plt.show()

## Dist

In [10]:
def dist(datasets, labels, drop_columns=None, rows=-1, cols=4):
    colors = ['#05b0a3', '#d68c78', '#c7f2a6', '#21deb2', '#deb221', '#de87cb']
    columns_list = datasets[0].select_dtypes(include=['float64', 'int64']).drop(columns=drop_columns).columns
    rows = math.ceil(len(columns_list) / cols)
    fig, axs = plt.subplots(rows, cols, figsize=(24, 5*rows))
    subtitle = f'Distribution for numerical features: {labels[0]}'
    for i in range(1, len(datasets)):
        subtitle += f' vs {labels[i]}'
    plt.suptitle(subtitle, fontsize=16, fontweight='bold')
    axs = axs.flatten()

    for i, col in enumerate(columns_list):
        for j in range(len(datasets)):
            sns.kdeplot(datasets[j][col], ax=axs[i], fill=True, alpha=0.5, linewidth=0.5, color=colors[j], label=labels[j])
            axis_title = f'{col}: {labels[0]} skewness: {datasets[0][col].skew():.2f}'
            for j in range(1, len(datasets)):
                axis_title += f'\n{labels[j]} skewness: {datasets[j][col].skew():.2f}'
            axs[i].set_title(axis_title)
        axs[i].legend()

        plt.tight_layout()

## Feature distribution

In [11]:
def feature_distribution(feature, val_feature, df):
    fig, axes = plt.subplots(1, 2, figsize=(16, 8))

    ax1 = axes[0]
    df_sort = df.groupby(val_feature)[feature].mean().sort_values(ascending=False).index
    sns.barplot(x=feature, y=val_feature, data=df, palette='light:#4caba4_r', order=df_sort,
                estimator=np.mean, ci=None, errwidth=0, ax=ax1)
    for p in ax1.patches:
        ax1.annotate(f'{p.get_width():.2f}', (p.get_x() + p.get_width() / 2., p.get_y() + p.get_height()),
            ha='center', va='center', xytext=(0, 20), textcoords='offset points', fontsize=10, color='black')
    ax1.set_title(f'Mean {feature} by {val_feature}')
    ax1.set_xlabel(feature)
    ax1.set_ylabel('')
    sns.despine(left=True, bottom=True, ax=ax1)

    # Violin Plot
    ax2 = axes[1]
    sns.violinplot(x=feature, y=val_feature, data=df, palette='light:#4caba4_r', order=df_sort, ax=ax2)
    ax2.set_title(f'Distribution of {feature} by {val_feature}')
    ax2.set_ylabel("")
    plt.yticks([])
    sns.despine(left=True, bottom=True, ax=ax2)
    plt.tight_layout()
    plt.show()

## Check outliers

In [12]:
def check_outliers(df, ncols=3, figsize_per_plot=(8, 3)):
    num_cols = df.select_dtypes(include=['float64', 'int64']).columns
    n = len(num_cols)

    if n == 0:
        print("Aucune colonne numérique.")
        return

    nrows = math.ceil(n / ncols)
    fig, axes = plt.subplots(
        nrows=nrows,
        ncols=ncols,
        figsize=(figsize_per_plot[0] * ncols, figsize_per_plot[1] * nrows)
    )

    if nrows == 1 and ncols == 1:
        axes = [axes]
    else:
        axes = axes.flatten()

    fig.suptitle('Outliers in the data', fontsize=18, fontweight='bold')

    for i, col in enumerate(num_cols):
        sns.boxplot(data=df, x=col, ax=axes[i])
        axes[i].set_title(col)
        axes[i].set_xlabel(col)
        axes[i].grid(False)

    for j in range(i + 1, len(axes)):
        fig.delaxes(axes[j])

    fig.tight_layout(rect=[0, 0, 1, 0.95])
    plt.show()

## Correlation

In [13]:
def correlation_heatmap(datasets, labels):
    fig, axes = plt.subplots(1, 2, figsize=(20, 10))

    for i in range(len(datasets)):
        corr = datasets[i].corr(method='pearson')
        mask = np.triu(np.ones_like(corr))
        sns.heatmap(corr, annot=True, fmt='.2f', mask=mask, cmap='copper_r', cbar=None, linewidth=2, ax=axes[i])
        axes[i].set_title(f'{labels[i]} Dataset', fontsize=16, fontweight='bold')

    plt.tight_layout()
    plt.show()

## Cross tab

In [ ]:
def cross_tab(row_data, col_data, df):
    ct = pd.crosstab(df[row_data], df[col_data])
    plt.figure(figsize=(10, 5))
    sns.heatmap(ct, annot=True, cmap='Blues', fmt='d', cbar=False)
    plt.title(f'{row_data} and {col_data}')
    plt.xlabel('')
    plt.ylabel('')
    plt.show()

# EDA

In [29]:
eda_df = df.copy()
eda_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7502 entries, 0 to 7501
Data columns (total 81 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   sample_id                                    7502 non-null   str
 1   source_dataset                               7502 non-null   str
 2   crop_type                                    7502 non-null   str
 3   location_country                             7502 non-null   str
 4   location_continent                           7502 non-null   str
 5   timestamp                                    7502 non-null   datetime64[us]
 6   sample_year                                  7502 non-null   float64
 7   toxin_name                                   7502 non-null   str
 8   toxin_value_raw                              7502 non-null   float64
 9   toxin_unit                                   7502 non-null   str
 10  toxin_value_standardized_ug_kg               7502 non-null   float64
 11  toxin_detected                               7502 non-null   bool
 12  fungal_species                               7502 non-null   str
 13  association_type                             7502 non-null   str
 14  original_metadata                            7502 non-null   str
 15  temperature_2m_mean_lag_1                    7502 non-null   float64
 16  temperature_2m_mean_lag_2                    7502 non-null   float64
 17  temperature_2m_mean_lag_3                    7502 non-null   float64
 18  temperature_2m_mean_lag_7                    7502 non-null   float64
 19  temperature_2m_mean_lag_14                   7502 non-null   float64
 20  temperature_2m_mean_lag_30                   7502 non-null   float64
 21  temperature_2m_mean_lag_60                   7502 non-null   float64
 22  temperature_2m_mean_mean_last_60obs          7502 non-null   float64
 23  temperature_2m_mean_std_last_60obs           7502 non-null   float64
 24  temperature_2m_mean_min_last_60obs           7502 non-null   float64
 25  temperature_2m_mean_max_last_60obs           7502 non-null   float64
 26  temperature_2m_mean_median_last_60obs        7502 non-null   float64
 27  temperature_2m_max_lag_1                     7502 non-null   float64
 28  temperature_2m_max_lag_2                     7502 non-null   float64
 29  temperature_2m_max_lag_3                     7502 non-null   float64
 30  temperature_2m_max_lag_7                     7502 non-null   float64
 31  temperature_2m_max_lag_14                    7502 non-null   float64
 32  temperature_2m_max_lag_30                    7502 non-null   float64
 33  temperature_2m_max_lag_60                    7502 non-null   float64
 34  temperature_2m_max_mean_last_60obs           7502 non-null   float64
 35  temperature_2m_max_std_last_60obs            7502 non-null   float64
 36  temperature_2m_max_min_last_60obs            7502 non-null   float64
 37  temperature_2m_max_max_last_60obs            7502 non-null   float64
 38  temperature_2m_max_median_last_60obs         7502 non-null   float64
 39  temperature_2m_min_lag_1                     7502 non-null   float64
 40  temperature_2m_min_lag_2                     7502 non-null   float64
 41  temperature_2m_min_lag_3                     7502 non-null   float64
 42  temperature_2m_min_lag_7                     7502 non-null   float64
 43  temperature_2m_min_lag_14                    7502 non-null   float64
 44  temperature_2m_min_lag_30                    7502 non-null   float64
 45  temperature_2m_min_lag_60                    7502 non-null   float64
 46  temperature_2m_min_mean_last_60obs           7502 non-null   float64
 47  temperature_2m_min_std_last_60obs            7502 non-null   float64
 48  temperature_2m_min_min_last_60obs            7502 non-null   float64
 49  temperature_2m_min_max_last_60obs            7502 non-null   float64
 50  temperature_2m_min_median_last_60obs         7502 non-null   float64
 51  relative_humidity_2m_mean_lag_1              7502 non-null   float64
 52  relative_humidity_2m_mean_lag_2              7502 non-null   float64
 53  relative_humidity_2m_mean_lag_3              7502 non-null   float64
 54  relative_humidity_2m_mean_lag_7              7502 non-null   float64
 55  relative_humidity_2m_mean_lag_14             7502 non-null   float64
 56  relative_humidity_2m_mean_lag_30             7502 non-null   float64
 57  relative_humidity_2m_mean_lag_60             7502 non-null   float64
 58  relative_humidity_2m_mean_mean_last_60obs    7502 non-null   float64
 59  relative_humidity_2m_mean_std_last_60obs     7502 non-null   float64
 60  relative_humidity_2m_mean_min_last_60obs     7502 non-null   float64
 61  relative_humidity_2m_mean_max_last_60obs     7502 non-null   float64
 62  relative_humidity_2m_mean_median_last_60obs  7502 non-null   float64
 63  precipitation_sum_lag_1                      7502 non-null   float64
 64  precipitation_sum_lag_2                      7502 non-null   float64
 65  precipitation_sum_lag_3                      7502 non-null   float64
 66  precipitation_sum_lag_7                      7502 non-null   float64
 67  precipitation_sum_lag_14                     7502 non-null   float64
 68  precipitation_sum_lag_30                     7502 non-null   float64
 69  precipitation_sum_lag_60                     7502 non-null   float64
 70  precipitation_sum_mean_last_60obs            7502 non-null   float64
 71  precipitation_sum_std_last_60obs             7502 non-null   float64
 72  precipitation_sum_min_last_60obs             7502 non-null   float64
 73  precipitation_sum_max_last_60obs             7502 non-null   float64
 74  precipitation_sum_median_last_60obs          7502 non-null   float64
 75  rainy_days_last_obs                          7502 non-null   int64
 76  precipitation_cumsum_last_obs                7502 non-null   float64
 77  precipitation_mean_last_obs                  7502 non-null   float64
 78  high_humidity_days_last_obs                  7502 non-null   int64
 79  hot_days_last_obs                            7502 non-null   int64
 80  cold_days_last_obs                           7502 non-null   int64
dtypes: bool(1), datetime64[us](1), float64(65), int64(4), str(10)
memory usage: 4.6 MB

## Distribution

## Correlation

# Data reduction
## View

## New computed dataframe

In [58]:
summary(sample_df).style.background_gradient()

In [59]:
summary(sample_df2).style.background_gradient()

In [60]:
final_df = sample_df.drop(columns=[
    'sample_id',
    'source_dataset',
    'location_country',
    'location_continent',
    'timestamp',
    'sample_year',
    'toxin_value_raw',
    'toxin_unit',
    'fungal_species',
    'association_type',
    'original_metadata',
    'year',
    'month',
    'day',
    'is_feed'
])

In [61]:
sample_df2

,origin_country_code,origin_country_label_fr,reporting_country_code,reporting_country_name,sample_country_code,sample_country_name,sample_date,sample_year,sample_month,sample_day,crop_group,product_name,sampling_point,param_name,zen_detected,zen_value_ug_kg,lod_ug_kg,loq_ug_kg,result_status,result_type,origin_matches_reporting_country,origin_matches_sample_country,sampling_strategy,program_type,sample_method,source_archive,source_file,resId_A,temperature_2m_mean_lag_1,temperature_2m_mean_lag_2,temperature_2m_mean_lag_3,temperature_2m_mean_lag_7,temperature_2m_mean_lag_14,temperature_2m_mean_lag_30,temperature_2m_mean_lag_60,temperature_2m_mean_mean_last_60obs,temperature_2m_mean_std_last_60obs,temperature_2m_mean_min_last_60obs,temperature_2m_mean_max_last_60obs,temperature_2m_mean_median_last_60obs,temperature_2m_max_lag_1,temperature_2m_max_lag_2,temperature_2m_max_lag_3,temperature_2m_max_lag_7,temperature_2m_max_lag_14,temperature_2m_max_lag_30,temperature_2m_max_lag_60,temperature_2m_max_mean_last_60obs,temperature_2m_max_std_last_60obs,temperature_2m_max_min_last_60obs,temperature_2m_max_max_last_60obs,temperature_2m_max_median_last_60obs,temperature_2m_min_lag_1,temperature_2m_min_lag_2,temperature_2m_min_lag_3,temperature_2m_min_lag_7,temperature_2m_min_lag_14,temperature_2m_min_lag_30,temperature_2m_min_lag_60,temperature_2m_min_mean_last_60obs,temperature_2m_min_std_last_60obs,temperature_2m_min_min_last_60obs,temperature_2m_min_max_last_60obs,temperature_2m_min_median_last_60obs,relative_humidity_2m_mean_lag_1,relative_humidity_2m_mean_lag_2,relative_humidity_2m_mean_lag_3,relative_humidity_2m_mean_lag_7,relative_humidity_2m_mean_lag_14,relative_humidity_2m_mean_lag_30,relative_humidity_2m_mean_lag_60,relative_humidity_2m_mean_mean_last_60obs,relative_humidity_2m_mean_std_last_60obs,relative_humidity_2m_mean_min_last_60obs,relative_humidity_2m_mean_max_last_60obs,relative_humidity_2m_mean_median_last_60obs,precipitation_sum_lag_1,precipitation_sum_lag_2,precipitation_sum_lag_3,precipitation_sum_lag_7,precipitation_sum_lag_14,precipitation_sum_lag_30,precipitation_sum_lag_60,precipitation_sum_mean_last_60obs,precipitation_sum_std_last_60obs,precipitation_sum_min_last_60obs,precipitation_sum_max_last_60obs,precipitation_sum_median_last_60obs,rainy_days_last_obs,precipitation_cumsum_last_obs,precipitation_mean_last_obs,high_humidity_days_last_obs,hot_days_last_obs,cold_days_last_obs,day_of_year,is_feed,toxin_name
0,CZ,Tchequie,CZ,Czechia,CZ,Czechia,2019-02-20,2019,2,20,other,Barley grain (feed),Primary production,Zearalenone,no,0.0,0.0,20.0,not_quantified_below_loq,Non Quantified Value ( less than LOQ),yes,yes,Objective sampling,Official (National) programme,NaN,CZ_latest_15410924_contaminants.zip,OCC_CHEMMON2020_CZ_2019.ZIP/OCC_CHEMMON2020_CZ...,CD4F4D661B734AD9E74B94A279E30233,3.11,2.21,2.06,1.76,-5.60,-5.69,4.78,-0.673000,3.081288,-7.60,4.78,0.125,10.82,10.73,9.87,4.81,-0.21,-0.61,7.12,2.572500,3.339529,-3.22,10.82,1.880,-1.86,-2.00,-2.85,-1.32,-9.07,-9.12,3.08,-3.406167,3.657951,-11.37,3.08,-2.210,87.80,81.54,85.13,89.72,95.99,89.72,97.44,91.419833,4.359728,76.43,97.44,92.560,0.17,0.00,0.01,0.35,0.12,0.00,9.28,2.029333,3.203704,0.0,17.86,0.685,55,121.76,2.029333,59,0,60,51,False,zearalenone
1,CZ,Tchequie,CZ,Czechia,CZ,Czechia,2019-03-18,2019,3,18,other,Barley grain (feed),Primary production,Zearalenone,no,0.0,0.0,20.0,not_quantified_below_loq,Non Quantified Value ( less than LOQ),yes,yes,Objective sampling,Official (National) programme,NaN,CZ_latest_15410924_contaminants.zip,OCC_CHEMMON2020_CZ_2019.ZIP/OCC_CHEMMON2020_CZ...,41CB40673B11DFD3300D20756321752A,9.15,6.72,6.18,2.21,7.80,2.31,1.76,1.032833,4.279331,-7.60,9.15,1.915,17.24,9.15,8.88,3.89,15.87,10.49,4.56,5.670667,5.214805,-3.22,17.24,4.920,2.94,4.12,2.26,0.27,3.84,-1.73,-0.94,-2.508167,4.202752,-11.37,4.12,-1.430,80.15,87.53,84.08,80.63,77.29,80.23,89.54,86.617333,6.646434,66.05,97.32,87.885,2.31,6.44,5.12,3.32,0.38,0.00,0.53,1.485333,3.036917,0.0,17.86,0.280,50,89.12,1.485333,53,0,60,77,False,zearalenone
2,CZ,Tchequie,CZ,Czechia,CZ,Czechia,2019-03-26,2019,3,26,other,Barley grain (feed),Storage,Zearalenone,no,0.0,0.0,20.0,not_quantified_below_loq,Non Quantified Value ( less than LOQ),yes,yes,Objective sampling,Official (National) programme,NaN,CZ_latest_15410924_contaminants.zip,OCC_CHEMMON2020_CZ_2019.ZIP/OCC_CHEMMON2020_CZ...,356CFC6AF1743F0E38EAACE24AD1EE34,4.36,7.88,10.52,2.08,2.33,0.15,-6.08,2.471167,3.908626,-6.97,10.52,2.320,8.01,11.37,18.39,6.52,6.31,5.12,-2.71,7.289000,5.036873,-2.71,18.39,7.765,1.11,5.02,4.44,-2.00,-0.43,-3.21,-8.52,-1.352167,3.846450,-11.37,5.02,-0.940,84.53,87.67,79.42,79.59,81.72,66.05,88.47,85.097667,7.438864,66.05,97.32,84.830,1.39,0.25,0.03,0.13,0.34,0.00,0.11,1.494333,3.036365,0.0,17.86,0.265,50,89.66,1.494333,47,0,59,85,False,zearalenone
3,CZ,Tchequie,CZ,Czechia,CZ,Czechia,2019-10-23,2019,10,23,other,Barley grain (feed),Storage,Zearalenone,no,0.0,0.0,20.0,not_quantified_below_loq,Non Quantified Value ( less than LOQ),yes,yes,Objective sampling,Official (National) programme,NaN,CZ_latest_15410924_contaminants.zip,OCC_CHEMMON2020_CZ_2019.ZIP/OCC_CHEMMON2020_CZ...,02DB9AA1D3A5A2F7F7383CCCAF04B6E8,13.17,13.88,11.81,11.78,11.54,14.01,20.94,14.496333,4.387305,5.38,23.88,14.015,19.37,20.60,18.97,16.10,16.42,20.93,26.27,20.359833,4.887286,11.29,31.07,20.100,8.87,9.63,7.96,8.41,8.79,6.79,16.03,9.405333,4.224141,-1.00,18.08,9.195,88.22,83.58,86.70,75.34,84.85,63.25,76.27,72.596333,9.556566,50.85,90.20,72.500,0.06,0.07,0.09,1.54,4.91,0.00,1.18,1.439500,2.846390,0.0,16.16,0.175,47,86.37,1.439500,16,11,9,296,False,zearalenone
4,CZ,Tchequie,CZ,Czechia,CZ,Czechia,2020-02-12,2020,2,12,other,Barley grain (feed),Storage,Zearalenone,no,0.0,0.0,20.0,not_quantified_below_loq,Non Quantified Value ( less than LOQ),yes,yes,Objective sampling,Official (National) programme,NaN,CZ_latest_15410924_contaminants.zip,OCC_CHEMMON2021_CZ_2020.ZIP/OCC_CHEMMON2021_CZ...,E0EB9B82C93581D42418FEA7CF28BADE,3.75,6.82,1.82,-0.52,0.47,0.52,2.00,1.387500,2.855486,-3.77,9.26,0.650,5.54,11.36,8.34,2.09,4.08,3.53,5.27,4.832667,2.863914,0.26,13.48,4.090,1.50,3.10,-2.53,-5.03,-1.48,-1.08,0.01,-0.995167,2.927107,-6.05,6.22,-1.550,74.35,76.60,86.60,87.21,88.50,95.69,92.05,91.894833,4.703351,74.35,97.94,92.520,2.42,6.93,0.28,2.75,0.48,0.05,2.54,1.583833,2.921914,0.0,18.07,0.250,56,95.03,1.583833,58,0,57,43,False,zearalenone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47,SK,Slovaquie,SK,Slovakia,SK,Slovakia,2023-09-19,2023,9,19,other,Common wheat grain,Primary production,Zearalenone,no,0.0,0.0,1.0,not_quantified_below_loq,Non Quantified Value ( less than LOQ),yes,yes,Selective sampling,Official (National) programme,Official sampling,SK_latest_15411469_contaminants.zip,OCC_CHEMMON2024_SK_2023.ZIP/OCC_CHEMMON2024_SK...,B74BFB4877BB720A50800B3B2A778D77,22.78,22.06,20.54,23.81,20.10,27.85,20.76,22.381167,3.243001,14.76,29.12,22.025,29.05,29.09,26.81,31.51,27.03,34.38,23.89,28.215167,4.222069,16.67,35.95,28.660,15.88,16.30,14.85,16.62,12.47,21.07,17.98,16.539167,2.992790,10.62,22.94,16.200,65.93,63.10,63.28,51.47,56.56,52.83,72.38,63.361000,9.783292,50.04,87.66,61.785,0.62,0.00,0.03,0.00,0.00,0.00,6.72,2.576167,4.620168,0.0,20.91,0.270,43,154.57,2.576167,4,47,0,262,False,zearalenone
48,SK,Slovaquie,SK,Slovakia,SK,Slovakia,2023-09-29,2023,9,29,other,Common wheat grain,Primary production,Zearalenone,no,0.0,3.0,10.0,not_quantified_below_loq,Non Quantified Value ( less than LOQ),yes,yes,Selective sampling,Official (National) programme,Official sampling,SK_latest_15411469_contaminants.zip,OCC_CHEMMON2024_SK_2023.ZIP/OCC_CHEMMON2024_SK...,2A9C36E2DBFAFB64CC108370298CD965,19.16,19.52,20.20,22.62,19.96,17.16,22.58,21.904500,3.357298,14.39,29.12,21.655,27.86,28.26,28.40,29.54,25.64,21.05,28.46,27.822167,4.411928,15.99,35.95,28.330,11.70,12.31,14.07,16.98,14.00,14.44,17.08,16.132833,3.016542,10.62,22.94,15.790,60.15,62.13,67.26,65.09,64.52,81.95,55.54,64.391167,10.111791,50.04,87.66,63.120,0.00,0.00,0.01,0.98,0.01,5.79,0.00,2.381833,4.465820,0.0,20.91,0.100,40,142.91,2.381833,6,47,0,272,False,zearalenone
49,SK,Slovaquie,SK,Slovakia,SK,Slovakia,2023-10-03,2023,10,3,other,Common wheat grain,Primary production,Zearalenone,no,0.0,0.0,8.0,not_quantified_below_loq,Non Quantified Value ( less than LOQ),yes,yes,Selective sampling,Official (National) programme,Official sampling,SK_latest_15411469_contaminants.zip,OCC_CHEMMON2024_SK_2023.ZIP/OCC_CHEMMON2024_SK...,310177CA51EE0AC37A0EA8389CAB5564,18.22,15.99,17.83,20.20,20.18,20.75,20.58,21.658667,3.516487,14.39,29.12,21.295,25.77,21.66,23.83,28.40,23.36,24.07,25.07,27.667500,4.506421,15.99,35.95,28.190,12.20,10.10,12.38,14.07,15.92,16.88,16.89,15.861333,3.185753,10.10,22.94,15.405,57.66,59.39,71.94,67.26,77.55,67.52,77.94,64.151833,10.118709,50.04,87.66,62.265,0.00,0.00,0.42,0.01,7.26,2.45,12.39,1.955500,3.739305,0.0,15.05,0.080,38,117.33,1.955500,6,45,0,276,False,zearalenone
50,SK,Slovaquie,SK,Slovakia,SK,Slovakia,2023-10-23,2023,10,23,other,Common wheat grain,Primary production,Zearalenone,no,0.0,0.0,1.0,not_quantified_below_loq,Non Quantified Value ( less than LOQ),yes,yes,Selective sampling,Official (National) programme,Official sampling,SK_latest_15411469_contaminants.zip,OCC_CHEMMON2024_SK_2023.ZIP/OCC_CHEMMON2024_SK...,72554C183712F1986234C00F4A63BFC4,15.65,19.50,19.74,8.59,13.22,17.61,26.60,19.240667,4.227196,8.31,28.15,19.510,20.06,23.85,25.60,14.04,20.76,19.14,33.03,25.481167,4.916903,14.04,35.10,25.705,11.96,15.96,14.99,3.77,6.59,14.15,19.57,13.530833,4.103746,1.56,22.40,14.015,72.83,74.03,74.63,62.65,66.70,81.24,54.46,64.846667,8.833226,50.22,84.25,63.580,3.51,3.19,0.38,0.03,5.49,7.30,0.02,1.519167,3.154241,0.0,15.05,0.065,40,91.15,1.519167,5,37,3,296,False,zearalenone
51,SK,Slovaquie,SK,Slovakia,SK,Slovakia,2023-11-06,2023,11,6,other,Common wheat grain,Primary production,Zearalenone,no,0.0,0.0,8.0,not_quantified_below_loq,Non Quantified Value ( less than LOQ),yes,yes,Selective sampling,Official (National) programme,Official sampling,SK_latest_15411469_contaminants.zip,OCC_CHEMMON2024_SK_2023.ZIP/OCC_CHEMMON2024_SK...,D25751426DB813350B94A2BCD4B94D14,10.02,7.94,10.61,15.74,14.05,17.27,21.31,16.950833,4.316435,7.94,23.81,17.445,13.79,12.61,12.97,22.10,20.50,25.36,28.85,23.027167,5.336745,12.61,31.51,23.595,7.80,5.08,6.10,11.39,9.21,9.78,13.82,11.557500,3.781178,1.56,17.24,11.980,87.11,81.14,86.81,82.60,71.68,55.78,52.67,68.836333,10.843139,50.22,91.86,66.815,15.07,0.01,13.43,0.06,0.01,0.00,0.00,2.411833,5.349198,0.0,30.94,0.075,42,144.71,2.411833,13,27,3,310,False,zearalenone

In [62]:
sample_df2['day_of_year'].value_counts()

day_of_year
234    13
131    10
152     8
235     8
229     7
       ..
64      1
215     1
208     1
256     1
310     1
Name: count, Length: 261, dtype: int64

In [63]:
final_df2 = sample_df2.drop(columns=[
    "origin_country_code",
    "origin_country_label_fr",
    "reporting_country_code",
    "reporting_country_name",
    "sample_country_code",
    "sample_country_name",
    "sample_date",
    "sample_year",
    "sample_month",
    "sample_day",
    "product_name",
    "sampling_point",
    "param_name",
    "lod_ug_kg",
    "loq_ug_kg",
    "result_status",
    "result_type",
    "origin_matches_reporting_country",
    "origin_matches_sample_country",
    "sampling_strategy",
    "program_type",
    "sample_method",
    "source_archive",
    "source_file",
    "resId_A",
    "is_feed",
])
final_df2 = final_df2.rename(columns={
    'zen_detected': 'toxin_detected',
    'zen_value_ug_kg': 'toxin_value_standardized_ug_kg'
})

In [64]:
final_df.columns

Index(['toxin_name', 'toxin_value_standardized_ug_kg', 'toxin_detected',
       'temperature_2m_mean_lag_1', 'temperature_2m_mean_lag_2',
       'temperature_2m_mean_lag_3', 'temperature_2m_mean_lag_7',
       'temperature_2m_mean_lag_14', 'temperature_2m_mean_lag_30',
       'temperature_2m_mean_lag_60', 'temperature_2m_mean_mean_last_60obs',
       'temperature_2m_mean_std_last_60obs',
       'temperature_2m_mean_min_last_60obs',
       'temperature_2m_mean_max_last_60obs',
       'temperature_2m_mean_median_last_60obs', 'temperature_2m_max_lag_1',
       'temperature_2m_max_lag_2', 'temperature_2m_max_lag_3',
       'temperature_2m_max_lag_7', 'temperature_2m_max_lag_14',
       'temperature_2m_max_lag_30', 'temperature_2m_max_lag_60',
       'temperature_2m_max_mean_last_60obs',
       'temperature_2m_max_std_last_60obs',
       'temperature_2m_max_min_last_60obs',
       'temperature_2m_max_max_last_60obs',
       'temperature_2m_max_median_last_60obs', 'temperature_2m_min_lag_1',
       'temperature_2m_min_lag_2', 'temperature_2m_min_lag_3',
       'temperature_2m_min_lag_7', 'temperature_2m_min_lag_14',
       'temperature_2m_min_lag_30', 'temperature_2m_min_lag_60',
       'temperature_2m_min_mean_last_60obs',
       'temperature_2m_min_std_last_60obs',
       'temperature_2m_min_min_last_60obs',
       'temperature_2m_min_max_last_60obs',
       'temperature_2m_min_median_last_60obs',
       'relative_humidity_2m_mean_lag_1', 'relative_humidity_2m_mean_lag_2',
       'relative_humidity_2m_mean_lag_3', 'relative_humidity_2m_mean_lag_7',
       'relative_humidity_2m_mean_lag_14', 'relative_humidity_2m_mean_lag_30',
       'relative_humidity_2m_mean_lag_60',
       'relative_humidity_2m_mean_mean_last_60obs',
       'relative_humidity_2m_mean_std_last_60obs',
       'relative_humidity_2m_mean_min_last_60obs',
       'relative_humidity_2m_mean_max_last_60obs',
       'relative_humidity_2m_mean_median_last_60obs',
       'precipitation_sum_lag_1', 'precipitation_sum_lag_2',
       'precipitation_sum_lag_3', 'precipitation_sum_lag_7',
       'precipitation_sum_lag_14', 'precipitation_sum_lag_30',
       'precipitation_sum_lag_60', 'precipitation_sum_mean_last_60obs',
       'precipitation_sum_std_last_60obs', 'precipitation_sum_min_last_60obs',
       'precipitation_sum_max_last_60obs',
       'precipitation_sum_median_last_60obs', 'rainy_days_last_obs',
       'precipitation_cumsum_last_obs', 'precipitation_mean_last_obs',
       'high_humidity_days_last_obs', 'hot_days_last_obs',
       'cold_days_last_obs', 'day_of_year', 'crop_group'],
      dtype='str')

In [65]:
final_df2.columns

Index(['crop_group', 'toxin_detected', 'toxin_value_standardized_ug_kg',
       'temperature_2m_mean_lag_1', 'temperature_2m_mean_lag_2',
       'temperature_2m_mean_lag_3', 'temperature_2m_mean_lag_7',
       'temperature_2m_mean_lag_14', 'temperature_2m_mean_lag_30',
       'temperature_2m_mean_lag_60', 'temperature_2m_mean_mean_last_60obs',
       'temperature_2m_mean_std_last_60obs',
       'temperature_2m_mean_min_last_60obs',
       'temperature_2m_mean_max_last_60obs',
       'temperature_2m_mean_median_last_60obs', 'temperature_2m_max_lag_1',
       'temperature_2m_max_lag_2', 'temperature_2m_max_lag_3',
       'temperature_2m_max_lag_7', 'temperature_2m_max_lag_14',
       'temperature_2m_max_lag_30', 'temperature_2m_max_lag_60',
       'temperature_2m_max_mean_last_60obs',
       'temperature_2m_max_std_last_60obs',
       'temperature_2m_max_min_last_60obs',
       'temperature_2m_max_max_last_60obs',
       'temperature_2m_max_median_last_60obs', 'temperature_2m_min_lag_1',
       'temperature_2m_min_lag_2', 'temperature_2m_min_lag_3',
       'temperature_2m_min_lag_7', 'temperature_2m_min_lag_14',
       'temperature_2m_min_lag_30', 'temperature_2m_min_lag_60',
       'temperature_2m_min_mean_last_60obs',
       'temperature_2m_min_std_last_60obs',
       'temperature_2m_min_min_last_60obs',
       'temperature_2m_min_max_last_60obs',
       'temperature_2m_min_median_last_60obs',
       'relative_humidity_2m_mean_lag_1', 'relative_humidity_2m_mean_lag_2',
       'relative_humidity_2m_mean_lag_3', 'relative_humidity_2m_mean_lag_7',
       'relative_humidity_2m_mean_lag_14', 'relative_humidity_2m_mean_lag_30',
       'relative_humidity_2m_mean_lag_60',
       'relative_humidity_2m_mean_mean_last_60obs',
       'relative_humidity_2m_mean_std_last_60obs',
       'relative_humidity_2m_mean_min_last_60obs',
       'relative_humidity_2m_mean_max_last_60obs',
       'relative_humidity_2m_mean_median_last_60obs',
       'precipitation_sum_lag_1', 'precipitation_sum_lag_2',
       'precipitation_sum_lag_3', 'precipitation_sum_lag_7',
       'precipitation_sum_lag_14', 'precipitation_sum_lag_30',
       'precipitation_sum_lag_60', 'precipitation_sum_mean_last_60obs',
       'precipitation_sum_std_last_60obs', 'precipitation_sum_min_last_60obs',
       'precipitation_sum_max_last_60obs',
       'precipitation_sum_median_last_60obs', 'rainy_days_last_obs',
       'precipitation_cumsum_last_obs', 'precipitation_mean_last_obs',
       'high_humidity_days_last_obs', 'hot_days_last_obs',
       'cold_days_last_obs', 'day_of_year', 'toxin_name'],
      dtype='str')

## Result

In [66]:
summary(final_df).style.background_gradient()

In [67]:
summary(final_df2).style.background_gradient()

# Pre-processing
## Methods

In [68]:
def get_variable_types(dataframe, exclude=None):
    if exclude is None:
        exclude = []
    continuous_vars = []
    categorical_vars = []

    for column in dataframe.columns:
	    if column not in exclude:
	        categorical_vars.append(column) if dataframe[column].dtype == 'str' else continuous_vars.append(column)

    return continuous_vars, categorical_vars

In [69]:
def confusion():
	plt.figure(figsize=(15, 6))
	conf_matrix = confusion_matrix(y_test, y_pred)
	conf_labels = [f'{i}' for i in range(conf_matrix.shape[0])]
	conf_matrix_df = pd.DataFrame(conf_matrix, columns=conf_labels, index=conf_labels)
	plt.imshow(conf_matrix, interpolation='nearest', cmap=plt.cm.Blues)
	plt.xticks(np.arange(conf_matrix.shape[0]), conf_labels, rotation=45)
	plt.yticks(np.arange(conf_matrix.shape[0]), conf_labels)
	plt.xlabel('Predicted Label')
	plt.ylabel('True Label')
	for i in range(conf_matrix.shape[0]):
	    for j in range(conf_matrix.shape[1]):
	        plt.text(j, i, str(conf_matrix[i, j]), ha='center', va='center', color='black')
	plt.grid(False)
	plt.show()

In [70]:
def feature_importances(model):
	feature_importance = model.feature_importances_
	feature_importance_df = pd.DataFrame({'Feature': X.columns, 'Importance': feature_importance})
	feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)
	plt.figure(figsize=(12, 50))
	sns.barplot(x='Importance', y='Feature', data=feature_importance_df)
	plt.title('Feature Importance')
	plt.xlabel('Importance')
	plt.ylabel('')
	sns.despine(left=True, bottom=True)
	plt.show()

## Model 1
### Encoding

In [ ]:
final_dfs = pd.concat([final_df, final_df2]).drop_duplicates()
final_dfs

In [ ]:
final_dfs["toxin_detected"] = final_dfs["toxin_detected"].replace({
    "yes": True,
    "no": False
}).astype(bool)
final_dfs["toxin_detected"]

In [ ]:
continuous_vars, categorical_vars = get_variable_types(final_dfs, ['toxin_detected'])
display(continuous_vars, categorical_vars)

In [ ]:
final_dfs['toxin_value_standardized_ug_kg'] = final_dfs['toxin_value_standardized_ug_kg'].fillna(0)
sample = final_dfs.copy()
sample.info()

In [ ]:
sample = pd.get_dummies(sample, columns=categorical_vars, drop_first=True)
print(f'The encoded dataset has {sample.shape[0]} rows and {sample.shape[1]} columns')

In [ ]:
sample.columns

### Split

In [ ]:
X = sample.copy()
y = X.pop('toxin_detected')
y_2 = X.pop('toxin_value_standardized_ug_kg')
display(X.shape, y.shape)

In [ ]:
X.columns

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
display(f"Train shape: {X_train.shape}", f"Test shape: {X_test.shape}")

In [ ]:
# showplot('toxin_detected', y)
y_train.value_counts()

In [ ]:
y_train.value_counts()

In [ ]:
# sc = StandardScaler()
# X_train = sc.fit_transform(X_train)
# X_test = sc.transform(X_test)

### Hyperparameters

In [ ]:
# def objective(trial, X, y):
#     # Define parameters to be optimized for the LGBMClassifier
#     param = {
#         "objective": "binary",
#         "metric": "binary_logloss",
#         "verbosity": -1,
#         "boosting_type": "gbdt",
#         "random_state": 42,
#         "learning_rate": trial.suggest_float("learning_rate", 0.001, 0.2),
#         "n_estimators": trial.suggest_int("n_estimators", 100, 1000),
#         "lambda_l1": trial.suggest_float("lambda_l1", 0.005, 0.015),
#         "lambda_l2": trial.suggest_float("lambda_l2", 0.02, 0.06),
#         "max_depth": trial.suggest_int("max_depth", 5, 20),
#         "colsample_bytree": trial.suggest_float("colsample_bytree", 0.3, 0.9),
#         "subsample": trial.suggest_float("subsample", 0.8, 1.0),
#         "min_child_samples": trial.suggest_int("min_child_samples", 5, 50),
#     }
#
#     cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
#     scores = []
#
#     for train_idx, valid_idx in cv.split(X, y):
#         X_tr, X_val = X.iloc[train_idx], X.iloc[valid_idx]
#         y_tr, y_val = y.iloc[train_idx], y.iloc[valid_idx]
#
#         lgbm_classifier = LGBMClassifier(**param)
#         lgbm_classifier.fit(X_tr, y_tr)
#         y_proba = lgbm_classifier.predict_proba(X_val)[:, 1]
#         scores.append(roc_auc_score(y_val, y_proba))
#
#     return np.mean(scores)
#
# # Train Test split
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
#
# # sampler for Optuna optimization using Tree-structured Parzen Estimator sampler
# sampler = optuna.samplers.TPESampler(seed=42)
#
# # Create a study object, run the optimization process and get best parameters
# study = optuna.create_study(direction="maximize", sampler=sampler)
# study.optimize(lambda trial: objective(trial, X, y), n_trials=100)
# best_params = study.best_params
#
# print('='*50)
# print(f"Best params: {best_params}")
# print(f"Best CV AUC: {study.best_value}")

In [ ]:
best_params = {
    "objective": "binary",
    "metric": "binary_logloss",
    "verbosity": -1,
    "boosting_type": "gbdt",
    "random_state": 42,
    'learning_rate': 0.009743961937494949,
    'n_estimators': 213,
    'lambda_l1': 0.013119235781722067,
    'lambda_l2': 0.03749389007648924,
    'max_depth': 18,
    'colsample_bytree': 0.45560483202639046,
    'subsample': 0.8431540916294574,
    'min_child_samples': 8
}

### Build model

In [ ]:
lgbm_classifier = LGBMClassifier(**best_params)
lgbm_classifier.fit(X_train, y_train)
lgbm_classifier.booster_.save_model("toxin_detection_classifier.txt")

y_pred = lgbm_classifier.predict(X_test)
y_pred_proba = lgbm_classifier.predict_proba(X_test)[:, 1]

acc = accuracy_score(y_test, y_pred)
auc = roc_auc_score(y_test, y_pred_proba)
f1 = f1_score(y_test, y_pred)

print(f"Test Accuracy: {acc}")
print(f"Test ROC AUC: {auc}")
print(f"Test F1-score: {f1}")

In [ ]:
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

## Confusion matrix

In [ ]:
confusion()

In [ ]:
feature_importances(lgbm_classifier)

## Model 2
### Encoding

In [ ]:
# continuous_vars_2, categorical_vars_2 = get_variable_types(final_df, ['toxin_detected', 'toxin_value_standardized_ug_kg'])
# display(continuous_vars_2, categorical_vars_2)

In [ ]:
# final_df['toxin_value_standardized_ug_kg'] = final_df['toxin_value_standardized_ug_kg'].fillna(0)
# sample = final_df.copy()
# sample['toxin_detected'] == True
# sample.info()

In [ ]:
# sample = pd.get_dummies(sample, columns=categorical_vars_2, drop_first=True)
# print(f'The encoded dataset has {sample.shape[0]} rows and {sample.shape[1]} columns')

### Split

In [ ]:
# X = sample.copy()
# X.columns
# y = X.pop('toxin_value_standardized_ug_kg')
# X.shape
X_2 = X[y]
y_2 = y_2[y]
display(X_2.shape, y_2.shape)

In [ ]:
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(X_2, y_2, test_size=0.2, random_state=42)
display(f"Train shape: {X_train_2.shape}", f"Test shape: {X_test_2.shape}")

In [ ]:
y_train_2.value_counts()

### Hyperparameters

In [ ]:
# def objective(trial, X, y):
#     # Define parameters to be optimized for the LGBMClassifier
#     param = {
#         "objective": "regression",
#         "metric": "rmse",
#         "verbosity": -1,
#         "boosting_type": "gbdt",
#         "random_state": 42,
#         "learning_rate": trial.suggest_float("learning_rate", 0.001, 0.2),
#         "n_estimators": trial.suggest_int("n_estimators", 100, 1000),
#         "lambda_l1": trial.suggest_float("lambda_l1", 0.005, 0.015),
#         "lambda_l2": trial.suggest_float("lambda_l2", 0.02, 0.06),
#         "max_depth": trial.suggest_int("max_depth", 5, 20),
#         "num_leaves": trial.suggest_int("num_leaves", 7, 255),
#         "colsample_bytree": trial.suggest_float("colsample_bytree", 0.3, 0.9),
#         "subsample": trial.suggest_float("subsample", 0.8, 1.0),
#         "min_child_samples": trial.suggest_int("min_child_samples", 5, 50),
#     }
#
#     cv = KFold(n_splits=5, shuffle=True, random_state=42)
#     scores = []
#
#     for train_idx, valid_idx in cv.split(X_train_2):
#         X_tr, X_val = X_train_2.iloc[train_idx], X_train_2.iloc[valid_idx]
#         y_tr, y_val = y_train_2.iloc[train_idx], y_train_2.iloc[valid_idx]
#
#         lgbm_regressor = LGBMRegressor(**param)
#         lgbm_regressor.fit(X_tr, y_tr)
#         pred = lgbm_regressor.predict(X_val)
#
#         scores.append(mean_squared_error(y_val, pred))
#
#     return np.mean(scores)
#
# # Train Test split
# # X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
#
# # sampler for Optuna optimization using Tree-structured Parzen Estimator sampler
# sampler = optuna.samplers.TPESampler(seed=42)
#
# # Create a study object, run the optimization process and get best parameters
# study = optuna.create_study(direction="maximize", sampler=sampler)
# study.optimize(lambda trial: objective(trial, X_2, y_2), n_trials=50)
# best_params = study.best_params
#
# print('='*50)
# print(f"Best params: {best_params}")

In [ ]:
best_params = {
    "objective": "regression",
    "metric": "rmse",
    "verbosity": -1,
    "boosting_type": "gbdt",
    "random_state": 42,
    'learning_rate': 0.0011634354652036005,
    'n_estimators': 717,
    'lambda_l1': 0.013217597158001457,
    'lambda_l2': 0.03417033228523668,
    'max_depth': 15,
    'num_leaves': 54,
    'colsample_bytree': 0.4581407459012575,
    'subsample': 0.84128095567905,
    'min_child_samples': 48
}

### Build model

In [ ]:
lgbm_regressor = LGBMRegressor(**best_params)
lgbm_regressor.fit(X_train_2, y_train_2)
lgbm_regressor.booster_.save_model("toxin_detection_regressor.txt")

y_pred_2 = lgbm_regressor.predict(X_test_2)

rmse = mean_squared_error(y_test_2, y_pred_2)
mae = mean_absolute_error(y_test_2, y_pred_2)
r2 = r2_score(y_test, y_pred)

print(f"Test RMSE: {rmse}")
print(f"Test MAE: {mae}")
print(f"Test R2-score: {r2}")

In [ ]:
for i in range(len(y_test)):
    print(f"Predicted: {y_pred_2[i]} ; True: {np.array(y_test_2)[i]}")

In [ ]:
min(np.array(y_pred_2))

In [ ]:
confusion()

In [ ]:
feature_importances(lgbm_regressor)